# Generated by Django 4.0.3 on 2022-03-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='distributor_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='Tarifa da Distribuidora'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='consumption',
            field=models.IntegerField(blank=True, null=True, verbose_name='Consumo(kWh)'),
        ),
    ]
