# Generated by Django 4.0.3 on 2023-03-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consumer_distributor_tax_alter_consumer_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP'),
        ),
    ]
